service: serverless-node-js-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: ./src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
