service: serverless-typescript-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DATABASE_URL_SSM_PARAM: ${env:DATABASE_URL_SSM_PARAM,"No Value Set"}
    STAGE: ${env:STAGE,"no stage set"}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL
      - AWS_REGION

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
